### ISSUE TITLE
pyglet.gl.lib.GLException

### ISSUE THREAD

**Issue by Etyl** [emmanuel-battesti/swarm-rescue#8]
Hi, I'm getting this error, I tried searching for some fixes but couldn't find any. Here is the error when I launch launcher.py :
```
The team 'SkySaviors' n°99, with tom, alice, bob, lea

*** Map: MyMapIntermediate01, special zones: none
Skipping antialiasing due missing hardware/driver support
Traceback (most recent call last):
  File "./src/swarm_rescue/launcher.py", line 202, in <module>
    launcher.go()
  File "./src/swarm_rescue/launcher.py", line 162, in go
    result = self.one_round(eval_config, num_round + 1)
  File "./src/swarm_rescue/launcher.py", line 106, in one_round
    playground = my_map.construct_playground(drone_type=MyDrone)
  File "/home/hippolyte/tournoi-drones/swarm-rescue/src/swarm_rescue/maps/map_intermediate_01.py", line 81, in construct_playground
    playground.add(drone, self._drones_pos[i])
  File "/home/hippolyte/tournoi-drones/swarm-rescue/env/src/spg/src/spg/playground/playground.py", line 500, in add
    self.add(
  File "/home/hippolyte/tournoi-drones/swarm-rescue/env/src/spg/src/spg/playground/playground.py", line 522, in add
    self.ray_compute.add(device)
  File "/home/hippolyte/tournoi-drones/swarm-rescue/env/src/spg/src/spg/agent/sensor/ray.py", line 195, in add
    self._update_buffers_and_shaders()
  File "/home/hippolyte/tournoi-drones/swarm-rescue/env/src/spg/src/spg/agent/sensor/ray.py", line 205, in _update_buffers_and_shaders
    self._id_shader, self._color_shader = self._generate_shaders()
  File "/home/hippolyte/tournoi-drones/swarm-rescue/env/src/spg/src/spg/agent/sensor/ray.py", line 183, in _generate_shaders
    id_shader = self.ctx.compute_shader(source=new_source)
  File "/home/hippolyte/tournoi-drones/swarm-rescue/env/lib/python3.8/site-packages/arcade/gl/context.py", line 987, in compute_shader
    return ComputeShader(self, source)
  File "/home/hippolyte/tournoi-drones/swarm-rescue/env/lib/python3.8/site-packages/arcade/gl/compute_shader.py", line 29, in __init__
    self._shader_obj = gl.glCreateShader(gl.GL_COMPUTE_SHADER)
  File "/home/hippolyte/tournoi-drones/swarm-rescue/env/lib/python3.8/site-packages/pyglet/gl/lib.py", line 114, in errcheck
    raise GLException('(0x%x): %s' % (error, msg))
pyglet.gl.lib.GLException: (0x500): Invalid enum. An unacceptable value is specified for an enumerated argument.

```

Here is also the output of python -m pyglet.info 

```
Platform
------------------------------------------------------------------------------
platform:  Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
release:   5.15.90.1-microsoft-standard-WSL2
machine:   x86_64

Python
------------------------------------------------------------------------------
implementation: CPython
sys.version: 3.8.18 (default, Aug 25 2023, 13:20:30) 
[GCC 11.4.0]
sys.maxint: 9223372036854775807
os.getcwd(): /home/hippolyte/tournoi-drones/swarm-rescue

pyglet
------------------------------------------------------------------------------
pyglet.version: 2.0.dev23
pyglet.compat_platform: linux
pyglet.__file__: /home/hippolyte/tournoi-drones/swarm-rescue/env/lib/python3.8/site-packages/pyglet/__init__.py
pyglet.options['audio'] = ('xaudio2', 'directsound', 'openal', 'pulse', 'silent')
pyglet.options['debug_font'] = False
pyglet.options['debug_gl'] = True
pyglet.options['debug_gl_trace'] = False
pyglet.options['debug_gl_trace_args'] = False
pyglet.options['debug_gl_shaders'] = False
pyglet.options['debug_graphics_batch'] = False
pyglet.options['debug_lib'] = False
pyglet.options['debug_media'] = False
pyglet.options['debug_texture'] = False
pyglet.options['debug_trace'] = False
pyglet.options['debug_trace_args'] = False
pyglet.options['debug_trace_depth'] = 1
pyglet.options['debug_trace_flush'] = True
pyglet.options['debug_win32'] = False
pyglet.options['debug_input'] = False
pyglet.options['debug_x11'] = False
pyglet.options['shadow_window'] = True
pyglet.options['vsync'] = None
pyglet.options['xsync'] = True
pyglet.options['xlib_fullscreen_override_redirect'] = False
pyglet.options['search_local_libs'] = True
pyglet.options['win32_gdi_font'] = False
pyglet.options['headless'] = False
pyglet.options['headless_device'] = 0
pyglet.options['win32_disable_shaping'] = False
pyglet.options['xinput_controllers'] = True

pyglet.window
------------------------------------------------------------------------------
display: <pyglet.canvas.xlib.XlibDisplay object at 0x7f66eb243430>
screens[0]: XlibScreen(display=<pyglet.canvas.xlib.XlibDisplay object at 0x7f66eb243430>, x=0, y=0, width=1920, height=1080, xinerama=0)
config['double_buffer'] = 1
config['stereo'] = 0
config['buffer_size'] = 24
config['aux_buffers'] = 0
config['sample_buffers'] = 0
config['samples'] = 0
config['red_size'] = 8
config['green_size'] = 8
config['blue_size'] = 8
config['alpha_size'] = 0
config['depth_size'] = 24
config['stencil_size'] = 0
config['accum_red_size'] = 0
config['accum_green_size'] = 0
config['accum_blue_size'] = 0
config['accum_alpha_size'] = 0
config['major_version'] = 3
config['minor_version'] = 3
config['forward_compatible'] = None
config['opengl_api'] = None
config['debug'] = None
context: XlibContextARB(id=140080017345216, share=XlibContextARB(id=140080008410880, share=None))

window.context._info
------------------------------------------------------------------------------
gl_info.get_version(): (4, 1)
gl_info.get_vendor(): Microsoft Corporation
gl_info.get_renderer(): D3D12 (Intel(R) Iris(R) Xe Graphics)
gl_info.get_extensions():
   GL_AMD_conservative_depth
   GL_AMD_draw_buffers_blend
   GL_AMD_gpu_shader_int64
   GL_AMD_multi_draw_indirect
   GL_AMD_shader_stencil_export
   GL_AMD_shader_trinary_minmax
   GL_AMD_texture_texture4
   GL_ANGLE_texture_compression_dxt3
   GL_ANGLE_texture_compression_dxt5
   GL_ARB_ES2_compatibility
   GL_ARB_ES3_compatibility
   GL_ARB_arrays_of_arrays
   GL_ARB_base_instance
   GL_ARB_blend_func_extended
   GL_ARB_buffer_storage
   GL_ARB_clear_buffer_object
   GL_ARB_clip_control
   GL_ARB_compressed_texture_pixel_storage
   GL_ARB_conditional_render_inverted
   GL_ARB_conservative_depth
   GL_ARB_copy_buffer
   GL_ARB_debug_output
   GL_ARB_depth_buffer_float
   GL_ARB_depth_clamp
   GL_ARB_direct_state_access
   GL_ARB_draw_buffers
   GL_ARB_draw_buffers_blend
   GL_ARB_draw_elements_base_vertex
   GL_ARB_draw_indirect
   GL_ARB_draw_instanced
   GL_ARB_explicit_attrib_location
   GL_ARB_explicit_uniform_location
   GL_ARB_fragment_coord_conventions
   GL_ARB_fragment_layer_viewport
   GL_ARB_fragment_shader
   GL_ARB_framebuffer_no_attachments
   GL_ARB_framebuffer_object
   GL_ARB_framebuffer_sRGB
   GL_ARB_get_program_binary
   GL_ARB_get_texture_sub_image
   GL_ARB_gpu_shader5
   GL_ARB_gpu_shader_fp64
   GL_ARB_gpu_shader_int64
   GL_ARB_half_float_pixel
   GL_ARB_half_float_vertex
   GL_ARB_indirect_parameters
   GL_ARB_instanced_arrays
   GL_ARB_internalformat_query
   GL_ARB_internalformat_query2
   GL_ARB_invalidate_subdata
   GL_ARB_map_buffer_alignment
   GL_ARB_map_buffer_range
   GL_ARB_multi_bind
   GL_ARB_multi_draw_indirect
   GL_ARB_occlusion_query2
   GL_ARB_parallel_shader_compile
   GL_ARB_pixel_buffer_object
   GL_ARB_point_sprite
   GL_ARB_program_interface_query
   GL_ARB_provoking_vertex
   GL_ARB_robust_buffer_access_behavior
   GL_ARB_robustness
   GL_ARB_sample_shading
   GL_ARB_sampler_objects
   GL_ARB_seamless_cube_map
   GL_ARB_separate_shader_objects
   GL_ARB_shader_atomic_counter_ops
   GL_ARB_shader_atomic_counters
   GL_ARB_shader_bit_encoding
   GL_ARB_shader_draw_parameters
   GL_ARB_shader_objects
   GL_ARB_shader_precision
   GL_ARB_shader_stencil_export
   GL_ARB_shader_storage_buffer_object
   GL_ARB_shader_subroutine
   GL_ARB_shader_texture_lod
   GL_ARB_shading_language_420pack
   GL_ARB_shading_language_include
   GL_ARB_shading_language_packing
   GL_ARB_stencil_texturing
   GL_ARB_sync
   GL_ARB_tessellation_shader
   GL_ARB_texture_buffer_object
   GL_ARB_texture_buffer_object_rgb32
   GL_ARB_texture_buffer_range
   GL_ARB_texture_compression_bptc
   GL_ARB_texture_compression_rgtc
   GL_ARB_texture_cube_map_array
   GL_ARB_texture_filter_anisotropic
   GL_ARB_texture_float
   GL_ARB_texture_gather
   GL_ARB_texture_multisample
   GL_ARB_texture_non_power_of_two
   GL_ARB_texture_query_levels
   GL_ARB_texture_query_lod
   GL_ARB_texture_rectangle
   GL_ARB_texture_rg
   GL_ARB_texture_rgb10_a2ui
   GL_ARB_texture_stencil8
   GL_ARB_texture_storage
   GL_ARB_texture_storage_multisample
   GL_ARB_texture_swizzle
   GL_ARB_timer_query
   GL_ARB_transform_feedback2
   GL_ARB_transform_feedback3
   GL_ARB_transform_feedback_instanced
   GL_ARB_uniform_buffer_object
   GL_ARB_vertex_array_bgra
   GL_ARB_vertex_array_object
   GL_ARB_vertex_attrib_64bit
   GL_ARB_vertex_attrib_binding
   GL_ARB_vertex_buffer_object
   GL_ARB_vertex_shader
   GL_ARB_vertex_type_10f_11f_11f_rev
   GL_ARB_vertex_type_2_10_10_10_rev
   GL_ARB_viewport_array
   GL_ATI_blend_equation_separate
   GL_ATI_texture_float
   GL_EXT_EGL_image_storage
   GL_EXT_EGL_sync
   GL_EXT_abgr
   GL_EXT_blend_equation_separate
   GL_EXT_debug_label
   GL_EXT_draw_buffers2
   GL_EXT_draw_instanced
   GL_EXT_framebuffer_blit
   GL_EXT_framebuffer_multisample
   GL_EXT_framebuffer_multisample_blit_scaled
   GL_EXT_framebuffer_object
   GL_EXT_framebuffer_sRGB
   GL_EXT_memory_object
   GL_EXT_memory_object_fd
   GL_EXT_packed_depth_stencil
   GL_EXT_packed_float
   GL_EXT_pixel_buffer_object
   GL_EXT_provoking_vertex
   GL_EXT_semaphore
   GL_EXT_semaphore_fd
   GL_EXT_shader_integer_mix
   GL_EXT_texture_array
   GL_EXT_texture_compression_dxt1
   GL_EXT_texture_compression_rgtc
   GL_EXT_texture_compression_s3tc
   GL_EXT_texture_filter_anisotropic
   GL_EXT_texture_integer
   GL_EXT_texture_sRGB
   GL_EXT_texture_sRGB_decode
   GL_EXT_texture_shared_exponent
   GL_EXT_texture_snorm
   GL_EXT_texture_swizzle
   GL_EXT_timer_query
   GL_EXT_transform_feedback
   GL_EXT_vertex_array_bgra
   GL_EXT_vertex_attrib_64bit
   GL_IBM_multimode_draw_arrays
   GL_KHR_context_flush_control
   GL_KHR_debug
   GL_KHR_no_error
   GL_KHR_parallel_shader_compile
   GL_KHR_robust_buffer_access_behavior
   GL_KHR_robustness
   GL_KHR_texture_compression_astc_ldr
   GL_KHR_texture_compression_astc_sliced_3d
   GL_MESA_pack_invert
   GL_MESA_shader_integer_functions
   GL_MESA_texture_signed_rgba
   GL_NV_conditional_render
   GL_NV_copy_image
   GL_NV_depth_clamp
   GL_NV_packed_depth_stencil
   GL_NV_vdpau_interop
   GL_OES_EGL_image
   GL_S3_s3tc

pyglet.gl.glx_info
------------------------------------------------------------------------------
context.is_direct(): 1
glx_info.get_server_vendor(): SGI
glx_info.get_server_version(): 1.4
glx_info.get_server_extensions():
   GLX_ARB_context_flush_control
   GLX_ARB_create_context
   GLX_ARB_create_context_no_error
   GLX_ARB_create_context_profile
   GLX_ARB_fbconfig_float
   GLX_ARB_framebuffer_sRGB
   GLX_ARB_multisample
   GLX_EXT_create_context_es_profile
   GLX_EXT_create_context_es2_profile
   GLX_EXT_fbconfig_packed_float
   GLX_EXT_framebuffer_sRGB
   GLX_EXT_import_context
   GLX_EXT_libglvnd
   GLX_EXT_no_config_context
   GLX_EXT_texture_from_pixmap
   GLX_EXT_visual_info
   GLX_EXT_visual_rating
   GLX_MESA_copy_sub_buffer
   GLX_OML_swap_method
   GLX_SGI_make_current_read
   GLX_SGIS_multisample
   GLX_SGIX_fbconfig
   GLX_SGIX_pbuffer
   GLX_SGIX_visual_select_group
glx_info.get_client_vendor(): Mesa Project and SGI
glx_info.get_client_version(): 1.4
glx_info.get_client_extensions():
   GLX_ARB_context_flush_control
   GLX_ARB_create_context
   GLX_ARB_create_context_no_error
   GLX_ARB_create_context_profile
   GLX_ARB_create_context_robustness
   GLX_ARB_fbconfig_float
   GLX_ARB_framebuffer_sRGB
   GLX_ARB_get_proc_address
   GLX_ARB_multisample
   GLX_EXT_buffer_age
   GLX_EXT_create_context_es2_profile
   GLX_EXT_create_context_es_profile
   GLX_EXT_fbconfig_packed_float
   GLX_EXT_framebuffer_sRGB
   GLX_EXT_import_context
   GLX_EXT_no_config_context
   GLX_EXT_swap_control
   GLX_EXT_swap_control_tear
   GLX_EXT_texture_from_pixmap
   GLX_EXT_visual_info
   GLX_EXT_visual_rating
   GLX_ATI_pixel_format_float
   GLX_INTEL_swap_event
   GLX_MESA_copy_sub_buffer
   GLX_MESA_query_renderer
   GLX_MESA_swap_control
   GLX_NV_float_buffer
   GLX_OML_swap_method
   GLX_OML_sync_control
   GLX_SGIS_multisample
   GLX_SGIX_fbconfig
   GLX_SGIX_pbuffer
   GLX_SGIX_visual_select_group
   GLX_SGI_make_current_read
   GLX_SGI_swap_control
   GLX_SGI_video_sync
glx_info.get_extensions():
   GLX_ARB_context_flush_control
   GLX_ARB_create_context
   GLX_ARB_create_context_no_error
   GLX_ARB_create_context_profile
   GLX_ARB_fbconfig_float
   GLX_ARB_framebuffer_sRGB
   GLX_ARB_get_proc_address
   GLX_ARB_multisample
   GLX_EXT_create_context_es2_profile
   GLX_EXT_create_context_es_profile
   GLX_EXT_fbconfig_packed_float
   GLX_EXT_framebuffer_sRGB
   GLX_EXT_import_context
   GLX_EXT_no_config_context
   GLX_EXT_texture_from_pixmap
   GLX_EXT_visual_info
   GLX_EXT_visual_rating
   GLX_MESA_copy_sub_buffer
   GLX_MESA_query_renderer
   GLX_OML_swap_method
   GLX_SGIS_multisample
   GLX_SGIX_fbconfig
   GLX_SGIX_pbuffer
   GLX_SGIX_visual_select_group
   GLX_SGI_make_current_read

pyglet.media
------------------------------------------------------------------------------
audio driver: <pyglet.media.drivers.silent.adaptation.SilentDriver object at 0x7f66dbaf4a00>

pyglet.media.ffmpeg
------------------------------------------------------------------------------
FFmpeg not available.

pyglet.media.drivers.openal
------------------------------------------------------------------------------
OpenAL not available.

pyglet.input.wintab
------------------------------------------------------------------------------
WinTab not available.
```

**Comment by emmanuel-battesti** [comment]
Hi,

Your problem seems to be linked to the use of OpenGL shaders. 
The calculations for emulating the lidar and semantic sensors of the drones are performed, via these shaders, directly on the graphics card. 

At the moment, I'm seeing this problem a lot with some Windows users. It's probably a problem with the graphic driver or the way Windows handles OpenGL. 
The calculations for emulating the lidar and semantic sensors of the drones are performed, via these shaders, directly on the graphics card. 

The initial problem doesn't seem to occur under Ubuntu. On some "more powerful" Windows machines (desktop), it also works correctly. 
Two solutions. If you can, change the machine or OS. 

If not, there's a CPU version of the calculation performed by the shaders, which can be activated by changing a parameter in the code. Simply **change the use_shaders parameter from True to False, line 29 in the _src/swarm_reçue/spg_overlay/gui_map/close_playground.py_ file**. 

The disadvantage of this manipulation is that it reduces performance. Calculations take longer when you have a lot of drones. 

Can you give it a try? Do you still encounter the same problem?

**Comment by Etyl** [comment]
Hi, I've changed use_shaders to False and now it works fine, thanks !
